// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oaeslntqvgbcxhbajmpy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9hZXNsbnRxdmdiY3hoYmFqbXB5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3OTkxOTQsImV4cCI6MjA2MjM3NTE5NH0.re1FfcIrt3wJRD7dWhOjDthUD9tD5q_nbTH4mO3eUSo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);